subcomponents:
  go-server:
    config:
      image:
        repository: andrebriggs.azurecr.io/go-docker-k8s-demo
        tag: "20190330.1"
  # cloud-native:
  #   config:
  #   subcomponents:
  prometheus-grafana:
    config:
    subcomponents:
      grafana:
        config:
          adminPassword: "CHANGEME"
